"""
Skill 生成器 - 使用 Koda 框架智能生成代码
"""
from pathlib import Path
from typing import Dict, Any, Optional, TYPE_CHECKING

from evoskill.core.llm import LLMProvider

if TYPE_CHECKING:
    from evoskill.evolution.designer import SkillDesign


class SkillGenerator:
    """
    Skill 生成器
    
    使用 Koda 框架实现智能代码生成。
    """
    
    def __init__(self, llm_provider: Optional[LLMProvider] = None):
        self.llm = llm_provider
        self.koda_adapter = None
        
        if llm_provider:
            # 延迟导入避免循环依赖
            from evoskill.coding_agent.koda_adapter import KodaAdapter
            self.koda_adapter = KodaAdapter(llm_provider)
    
    async def generate(
        self,
        design: "SkillDesign",
        output_dir: Path,
    ) -> Dict[str, Path]:
        """
        生成完整的 Skill 文件
        
        使用 Pi Coding 框架完成完整的开发流程：
        1. 需求分析与技术规划
        2. 代码实现
        3. 测试验证
        4. 反思修复
        
        Args:
            design: Skill 设计
            output_dir: 输出目录
            
        Returns:
            生成的文件路径字典
        """
        skill_dir = output_dir / design.name
        skill_dir.mkdir(parents=True, exist_ok=True)
        
        tests_dir = skill_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        
        # 使用 Koda 开发
        if self.koda_adapter:
            print(f"[Generator] 启动 Koda 开发 {design.name}...")
            result = await self.koda_adapter.develop_skill(design)
            
            if not result.success:
                print(f"[Generator] 警告: Pi Coding 开发未完全成功")
                print(f"[Generator] 错误: {result.error_message}")
        else:
            # 降级：使用简单模板（备用）
            print(f"[Generator] 警告: 未配置 LLM，使用备用模板")
            from koda.core.types import CodeArtifact
            
            result = self._fallback_generate(design)
        
        # 写入文件
        generated_files = {}
        
        # 写入所有产物
        for artifact in result.artifacts:
            file_path = skill_dir / artifact.filename
            
            # 测试文件放到 tests 目录
            if artifact.filename.startswith("test_"):
                file_path = tests_dir / artifact.filename
            
            file_path.write_text(artifact.content, encoding="utf-8")
            
            # 记录生成的文件
            key = artifact.filename.replace(".", "_")
            generated_files[key] = file_path
        
        # 确保有 SKILL.md
        if "README.md" in [a.filename for a in result.artifacts]:
            # 复制 README.md 为 SKILL.md（EvoSkill 需要）
            readme_content = ""
            for a in result.artifacts:
                if a.filename == "README.md":
                    readme_content = a.content
                    break
            
            # 添加 frontmatter
            skill_md = f"""---
name: {design.name}
description: {design.description}
version: {design.version or "0.1.0"}
author: {design.author or "Pi Coding"}
---

{readme_content}
"""
            skill_md_path = skill_dir / "SKILL.md"
            skill_md_path.write_text(skill_md, encoding="utf-8")
            generated_files["skill_md"] = skill_md_path
        
        # __init__.py
        init_py_path = skill_dir / "__init__.py"
        init_py_path.write_text("# Skill package\n", encoding="utf-8")
        
        print(f"[Generator] {design.name} 生成完成，迭代 {result.iterations} 次")
        
        return generated_files
    
    def _fallback_generate(self, design: "SkillDesign") -> "TaskResult":
        """
        备用生成（无 LLM 时使用简单模板）
        """
        from koda.core.task import TaskResult, Task
        from pi_coding.core.types import CodeArtifact, TaskStatus
        
        skill_name = design.name
        
        # 生成 main.py
        tools_code = []
        for tool in design.tools:
            params = ", ".join([
                f"{n}: str" for n in tool.parameters.keys()
            ])
            tools_code.append(f"""
async def {tool.name}({params}) -> Dict[str, Any]:
    \"\"\"
    {tool.description}
    \"\"\"
    # TODO: 实现具体功能
    return {{"success": False, "error": "功能待实现"}}
""")
        
        main_py = f"\"\"\"\n{design.description}\n\"\"\"\n\n"
        main_py += "import asyncio\nfrom typing import Optional, Dict, Any, List\n\n"
        main_py += "\n".join(tools_code)
        main_py += f"""

SKILL_NAME = "{skill_name}"
SKILL_VERSION = "0.1.0"
SKILL_DESCRIPTION = "{design.description}"
SKILL_TOOLS = [
    {{"name": "{design.tools[0].name if design.tools else 'example'}", "description": "{design.tools[0].description if design.tools else '示例'}", "handler": {design.tools[0].name if design.tools else 'example'}}}
] if True else []

async def main():
    print(f"{{SKILL_NAME}} v{{SKILL_VERSION}}")

if __name__ == "__main__":
    asyncio.run(main())
"""
        
        # 生成文档
        doc = f"""# {skill_name}

{design.description}

## 注意

本 Skill 使用备用模板生成，功能尚未实现。

---

Generated by EvoSkill (fallback mode)
"""
        
        # 测试
        test_py = """import pytest

async def test_placeholder():
    assert True
"""
        
        artifacts = [
            CodeArtifact(filename="main.py", content=main_py, language="python"),
            CodeArtifact(filename="README.md", content=doc, language="markdown"),
            CodeArtifact(filename="test_main.py", content=test_py, language="python"),
        ]
        
        return TaskResult(
            task=Task(description="fallback"),
            success=True,
            status=TaskStatus.COMPLETED,
            artifacts=artifacts,
            iterations=0,
        )
