"""
Executor - 代码执行器

根据计划生成实际可运行的代码
"""
from typing import List, Dict, Any, Optional

from koda.core.task import Task, Plan, Step
from koda.core.types import ExecutionResult, CodeArtifact, TaskStatus


class Executor:
    """
    代码执行器
    
    将计划转换为实际代码
    """
    
    def __init__(self, llm: Any, tools: Optional[List] = None):
        self.llm = llm
        self.tools = tools or []
    
    async def execute(self, plan: Plan, task: Task) -> ExecutionResult:
        """
        执行计划生成代码
        """
        artifacts = []
        
        try:
            # 生成主代码文件
            main_code = await self._generate_main_code(plan, task)
            artifacts.append(CodeArtifact(
                filename="main.py",
                content=main_code,
                language="python",
                description="Main program",
            ))
            
            # 生成文档
            doc = await self._generate_documentation(plan, task)
            artifacts.append(CodeArtifact(
                filename="README.md",
                content=doc,
                language="markdown",
                description="Documentation",
            ))
            
            # 生成测试
            test_code = await self._generate_tests(plan, task, main_code)
            artifacts.append(CodeArtifact(
                filename="test_main.py",
                content=test_code,
                language="python",
                description="Tests",
            ))
            
            return ExecutionResult(
                success=True,
                output="Code generated successfully",
                artifacts=artifacts,
            )
            
        except Exception as e:
            return ExecutionResult(
                success=False,
                error=str(e),
                artifacts=artifacts,
            )
    
    async def _generate_main_code(self, plan: Plan, task: Task) -> str:
        """生成主代码"""
        api_info = "\n".join([
            f"# - {api.name}: {api.signup_url} (env: {api.env_var})"
            for api in plan.apis[:2]
        ])
        
        deps = "\n".join([f"# - {dep}" for dep in plan.dependencies])
        
        prompt = f"""Write complete Python code for:

{task.to_prompt()}

Approach: {plan.approach}

APIs: {api_info if api_info else '# Use standard library'}

Requirements:
1. Complete, runnable code
2. Use standard library prefer
3. Read API keys from env vars
4. Full error handling
5. Return format: {{"success": bool, "result": any}}

Output: Complete Python code only, no explanations.
"""
        
        code = await self.llm.complete(prompt)
        return self._clean_code(code)
    
    async def _generate_documentation(self, plan: Plan, task: Task) -> str:
        """生成文档"""
        api_sections = []
        for api in plan.apis:
            section = f"""### {api.name}
- Provider: {api.provider}
- Signup: {api.signup_url}
- Env var: `{api.env_var}`
- Free quota: {api.free_quota}
"""
            api_sections.append(section)
        
        return f"""# {task.description[:30]}

{task.description}

## API Setup

{chr(10).join(api_sections) if api_sections else 'No external APIs needed.'}

## Usage

```bash
python main.py
```

---
Generated by Koda
"""
    
    async def _generate_tests(
        self, 
        plan: Plan, 
        task: Task, 
        main_code: str
    ) -> str:
        """生成测试代码"""
        return """import pytest

async def test_placeholder():
    assert True
"""
    
    def _clean_code(self, code: str) -> str:
        """清理代码块"""
        code = code.strip()
        if code.startswith("```python"):
            code = code[9:]
        elif code.startswith("```"):
            code = code[3:]
        if code.endswith("```"):
            code = code[:-3]
        return code.strip()
